services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: soa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  auth1:
    build: ./services/auth
    environment:
      PORT: 8081
      INSTANCE_NAME: AUTH1
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: soa
      JWT_SECRET: super-secret-dev-key
    depends_on:
      - db

  auth2:
    build: ./services/auth
    environment:
      PORT: 8081
      INSTANCE_NAME: AUTH2
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: soa
      JWT_SECRET: super-secret-dev-key
    depends_on:
      - db


  faas:
    build: ./services/faas
    environment:
      PORT: 8083
    
  post1:
    build: ./services/post
    environment:
      PORT: 8082
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: soa
      JWT_SECRET: super-secret-dev-key
    depends_on:
      - db
  post2:
    build: ./services/post
    environment:
      PORT: 8082
      PGHOST: db
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: soa
      JWT_SECRET: super-secret-dev-key
    depends_on:
      - db


  gateway:
    image: nginx:alpine
    ports:
    - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - auth1
      - post1
      - faas
      - auth2
      - post2

volumes:
  dbdata:
